"""Core action schemas for the minimal OCL interface.

These objects define the first formal boundary between:

- what an internal agent *wants* to do (`RawAction`)
- what the control layer actually *allows* to happen (`ExecutableAction`)

The goal is to move away from prompt-only conventions and toward explicit,
inspectable action objects.


中文翻译：Core action schemas for the minimal OCL interface。"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class ActionRole(str, Enum):
    """Canonical actor roles used by the minimal OCL layer.

中文翻译：Canonical actor roles used by the minimal OCL layer。"""

    BUYER = "buyer"
    SELLER = "seller"
    PLATFORM = "platform"
    EXPERT = "expert"
    USER = "user"
    UNKNOWN = "unknown"


class ActionIntent(str, Enum):
    """High-level semantic intent of an action proposal.

中文翻译：High-level semantic intent of an action proposal。"""

    NEGOTIATE_PRICE = "negotiate_price"
    ACCEPT_DEAL = "accept_deal"
    REJECT_DEAL = "reject_deal"
    REQUEST_INFO = "request_info"
    EXPLAIN_POLICY = "explain_policy"
    ESCALATE = "escalate"
    TOOL_CALL = "tool_call"
    OTHER = "other"


class ControlDecision(str, Enum):
    """Canonical decision returned by the OCL control mapping.

中文翻译：Canonical decision returned by the OCL control mapping。"""

    APPROVE = "approve"
    REWRITE = "rewrite"
    BLOCK = "block"
    ESCALATE = "escalate"


@dataclass(slots=True)
class RawAction:
    """Proposed action before OCL validation or transformation.

    Inputs:
        actor_id: Stable identifier of the actor that produced the action.
        actor_role: Functional role of that actor in the current episode.
        utterance: The original natural-language proposal generated by the
            actor. This is the pre-control text.
        intent: Coarse semantic label describing what the actor is trying to
            achieve.
        proposed_price: Optional numeric price extracted upstream or proposed by
            the actor.
        tool_intent: Optional tool or side-effect request attached to the
            action.
        metadata: Free-form structured information preserved for audit and later
            control steps.

    Outputs:
        A structured object that can be checked by role policy, constraints,
        risk gating, attribution, and audit code.
    

    中文翻译：Proposed action before OCL validation or transformation。"""

    actor_id: str
    actor_role: ActionRole = ActionRole.UNKNOWN
    utterance: str = ""
    intent: ActionIntent = ActionIntent.OTHER
    proposed_price: float | None = None
    tool_intent: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class ExecutableAction:
    """Action approved or rewritten by the OCL for downstream execution.

    Inputs:
        actor_id: Stable identifier of the actor whose proposal was evaluated.
        actor_role: Functional role associated with the action.
        approved: Whether the action passed the current control policy.
        decision: Canonical OCL decision type.
        final_text: The text that should actually be sent to the environment or
            downstream system.
        intent: The semantic intent after any control-layer rewriting.
        final_price: Optional numeric price that the environment should treat as
            the effective offer.
        blocked_reason: Human-readable explanation when the action is rejected
            or downgraded.
        requires_confirmation: Whether the action may proceed only after an
            explicit confirmation step.
        requires_escalation: Whether the action should trigger a higher-level
            controller, expert, or human handoff.
        metadata: Free-form structured payload retained for execution and audit.

    Outputs:
        A control-layer-sanctioned action object that can be translated into
        environment calls or tool invocations.
    

    中文翻译：Action approved or rewritten by the OCL for downstream execution。"""

    actor_id: str
    actor_role: ActionRole = ActionRole.UNKNOWN
    approved: bool = True
    decision: ControlDecision = ControlDecision.APPROVE
    final_text: str = ""
    intent: ActionIntent = ActionIntent.OTHER
    final_price: float | None = None
    blocked_reason: str | None = None
    requires_confirmation: bool = False
    requires_escalation: bool = False
    metadata: dict[str, Any] = field(default_factory=dict)
