"""Translate AgenticPay-style text messages into minimal OCL action objects.

中文翻译：Translate AgenticPay-style text messages into minimal OCL action objects。"""

from __future__ import annotations

import re

from aimai_ocl.schemas.actions import (
    ActionIntent,
    ActionRole,
    ControlDecision,
    ExecutableAction,
    RawAction,
)


PRICE_PATTERNS = (
    r"###\s*(?:BUYER_PRICE|SELLER_PRICE)\s*\(\$([\d,]+\.?\d*)\)\s*###",
    r"###\s*\$([\d,]+\.?\d*)\s*###",
    r"\$([\d,]+\.?\d*)",
)


def extract_price_from_text(text: str) -> float | None:
    """Extract the last positive price-like value from a text action.

    Args:
        text: Natural-language message emitted by an AgenticPay buyer or seller.

    Returns:
        A positive float if a price-like token can be found; otherwise ``None``.
    

    中文翻译：Extract the last positive price-like value from a text action。"""
    for pattern in PRICE_PATTERNS:
        matches = re.findall(pattern, text, flags=re.IGNORECASE)
        if matches:
            try:
                value = float(matches[-1].replace(",", ""))
            except ValueError:
                continue
            if value > 0:
                return value
    return None


def infer_intent_from_text(text: str) -> ActionIntent:
    """Infer a coarse action intent from a raw AgenticPay message.

    Args:
        text: Natural-language buyer or seller message.

    Returns:
        The inferred high-level ``ActionIntent``. This is intentionally simple
        and only supports the minimal OCL scaffold.
    

    中文翻译：推断 a coarse action intent from a raw AgenticPay message。"""
    upper_text = text.upper()
    if "MAKE_DEAL" in upper_text:
        return ActionIntent.ACCEPT_DEAL
    if "?" in text:
        return ActionIntent.REQUEST_INFO
    if extract_price_from_text(text) is not None:
        return ActionIntent.NEGOTIATE_PRICE
    return ActionIntent.OTHER


def raw_action_from_text(
    actor_id: str,
    actor_role: ActionRole,
    text: str,
) -> RawAction:
    """Build a minimal ``RawAction`` from an AgenticPay text action.

    Args:
        actor_id: Stable identifier of the actor who produced the message.
        actor_role: Role associated with that actor.
        text: Original text message generated by the actor.

    Returns:
        A ``RawAction`` object capturing the text, inferred intent, and any
        extracted price.
    

    中文翻译：构建 a minimal ``RawAction`` from an AgenticPay text action。"""
    return RawAction(
        actor_id=actor_id,
        actor_role=actor_role,
        utterance=text,
        intent=infer_intent_from_text(text),
        proposed_price=extract_price_from_text(text),
    )


def executable_action_from_raw(raw_action: RawAction) -> ExecutableAction:
    """Create the default pass-through executable action for the scaffold.

    Args:
        raw_action: The original action proposed by a buyer or seller.

    Returns:
        An ``ExecutableAction`` that mirrors the raw action with no gating or
        rewriting yet. Later OCL controllers will replace this pass-through
        behavior with real control logic.
    

    中文翻译：创建 the default pass-through executable action for the scaffold。"""
    return ExecutableAction(
        actor_id=raw_action.actor_id,
        actor_role=raw_action.actor_role,
        approved=True,
        decision=ControlDecision.APPROVE,
        final_text=raw_action.utterance,
        intent=raw_action.intent,
        final_price=raw_action.proposed_price,
    )
